### ISSUE TITLE
Request For Tag Enablement

### ISSUE THREAD

**Issue by sandeepgopi** [cloudposse/terraform-aws-cloudwatch-logs#30]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug

When we began using the repo, we found that one of the resource is yet to be tag enabled. Hence when our internal projects were calling this repo, our custom tags were not being added in AWS. Please can you enable tags for the below.

Resource (In the main.tf file): "aws_cloudwatch_log_group"
Resource name: "default"

Description : Request you to implement a map(string) variable called tags and ensure this is implemented for:
The ''aws_cloudwatch_log_group" resource with 'default' resource name

## Steps to Reproduce
2. Run '....'
3. Enter '....'

## Screenshots
If applicable, add screenshots or logs to help explain your problem.

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: [e.g. Linux, OSX, WSL, etc]
 - Version [e.g. 10.15]

**Comment by nitrocode** [comment]
Tags are currently enabled.

See this code block.

https://github.com/cloudposse/terraform-aws-cloudwatch-logs/blob/1dc6e978604c43a182ba40dce8f2f55a25e0d39a/main.tf#L5-L21

If you use the `tags` input for this module, then each resource should be tagged appropriately.

Here is an example

```hcl
module "cloudwatch_logs" {
  source  = "cloudposse/cloudwatch-logs/aws"
  # Cloud Posse recommends pinning every module to a specific version
  # version = "x.x.x"

  namespace    = "eg"
  stage        = "prod"
  name         = "app"
  stream_names = ["kafka-instance-1", "kafka-instance-2"]

  tags = {
    fruit = "banana"
  }
}
```

**Comment by sandeepgopi** [comment]
Hi @nitrocode . Hope you are doing well. Thank you for the information.
We apply tags in the following way

Pass tags to the repository from an external file.

In this repo:
define tags as a map (string) variable in variables.tf
The tags are then applied using the below line in main.tf
"tags = var.tags"

Is it possible to support this way of tagging in the terraform-aws-cloudwatch-logs repo?
Thank You


Regards

**Comment by nitrocode** [comment]
@sandeepgopi of course!

```hcl
module "cloudwatch_logs" {
  source  = "cloudposse/cloudwatch-logs/aws"
  # Cloud Posse recommends pinning every module to a specific version
  # version = "x.x.x"

  # ...

  tags = var.tags
}
```

simple as that 😄

**Comment by sandeepgopi** [comment]
Hi @nitrocode .
Thank you for your update. As this is your repo, is it fine for us to do this change (tags = var.tags). Or do we need to fork it and change :) 

Thank You 


Kind Regards
Sandeep

**Comment by nitrocode** [comment]
not sure i understand.. you can pass tags to this module without having to fork the repo
